/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



package hn.jairo.sierra.pa1.aplicacion;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author usuario
 */
public class FRM_ELECCIONES_JAIRO_SIERRA extends javax.swing.JFrame {

    /**
     * Creates new form FRM_ELECCIONES_JAIRO_SIERRA
     */
    public FRM_ELECCIONES_JAIRO_SIERRA() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagenFondo= new ImageIcon(getClass().getResource("/IMAGENES/astronaut-1784245_1280.jpg"));
        Icon fondo = new ImageIcon(imagenFondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(fondo);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    
    
    
            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtgot = new javax.swing.JTextField();
        lblpergot = new javax.swing.JLabel();
        lblvotogot = new javax.swing.JLabel();
        btngot = new javax.swing.JButton();
        lblGOT1 = new javax.swing.JLabel();
        txtpergot = new javax.swing.JTextField();
        lblperbbad = new javax.swing.JLabel();
        lblvotobbad = new javax.swing.JLabel();
        txtbbad = new javax.swing.JTextField();
        txtperbbad = new javax.swing.JTextField();
        btnbbad = new javax.swing.JButton();
        lblBBAD = new javax.swing.JLabel();
        lblvototsop = new javax.swing.JLabel();
        txtpertsop = new javax.swing.JTextField();
        txttsop = new javax.swing.JTextField();
        lblpertsop = new javax.swing.JLabel();
        btntsop = new javax.swing.JButton();
        lblTSOP = new javax.swing.JLabel();
        lbltotalvotos = new javax.swing.JLabel();
        btnganador = new javax.swing.JButton();
        txttotalvotos = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        lblTituliPrincipal4 = new javax.swing.JLabel();
        lblTituliPrincipal3 = new javax.swing.JLabel();
        lblTituloGOT = new javax.swing.JLabel();
        lblTituliPrincipal1 = new javax.swing.JLabel();
        lblTituliPrincipal = new javax.swing.JLabel();
        lblsubfondo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgotActionPerformed(evt);
            }
        });
        getContentPane().add(txtgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 60, 30));

        lblpergot.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblpergot.setForeground(new java.awt.Color(255, 255, 255));
        lblpergot.setText("%");
        getContentPane().add(lblpergot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, 20));

        lblvotogot.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblvotogot.setForeground(new java.awt.Color(255, 255, 255));
        lblvotogot.setText("Votes");
        getContentPane().add(lblvotogot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 60, -1));

        btngot.setFont(new java.awt.Font("Cinzel Black", 0, 12)); // NOI18N
        btngot.setText("Vote");
        btngot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngotActionPerformed(evt);
            }
        });
        getContentPane().add(btngot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 150, 30));

        lblGOT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/got.jpg"))); // NOI18N
        getContentPane().add(lblGOT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 290, 190));

        txtpergot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpergotActionPerformed(evt);
            }
        });
        getContentPane().add(txtpergot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 60, 30));

        lblperbbad.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblperbbad.setForeground(new java.awt.Color(255, 255, 255));
        lblperbbad.setText("%");
        getContentPane().add(lblperbbad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 30, 30));

        lblvotobbad.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblvotobbad.setForeground(new java.awt.Color(255, 255, 255));
        lblvotobbad.setText("Votes");
        getContentPane().add(lblvotobbad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 60, 20));
        getContentPane().add(txtbbad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 60, 30));
        getContentPane().add(txtperbbad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 60, 30));

        btnbbad.setFont(new java.awt.Font("Cinzel Black", 0, 12)); // NOI18N
        btnbbad.setText("Vote");
        btnbbad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbbadActionPerformed(evt);
            }
        });
        getContentPane().add(btnbbad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 150, 30));

        lblBBAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bbad.jpg"))); // NOI18N
        getContentPane().add(lblBBAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 260, 180));

        lblvototsop.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblvototsop.setForeground(new java.awt.Color(255, 255, 255));
        lblvototsop.setText("Votes");
        getContentPane().add(lblvototsop, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 60, 20));

        txtpertsop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpertsopActionPerformed(evt);
            }
        });
        getContentPane().add(txtpertsop, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 60, 30));
        getContentPane().add(txttsop, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 60, 30));

        lblpertsop.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblpertsop.setForeground(new java.awt.Color(255, 255, 255));
        lblpertsop.setText("%");
        getContentPane().add(lblpertsop, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, 30));

        btntsop.setFont(new java.awt.Font("Cinzel Black", 0, 12)); // NOI18N
        btntsop.setText("Vote");
        btntsop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntsopActionPerformed(evt);
            }
        });
        getContentPane().add(btntsop, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 150, 30));

        lblTSOP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/tsop.jpg"))); // NOI18N
        getContentPane().add(lblTSOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 260, 180));

        lbltotalvotos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbltotalvotos.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalvotos.setText("Total Votes");
        getContentPane().add(lbltotalvotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 90, 20));

        btnganador.setFont(new java.awt.Font("Cinzel Black", 1, 18)); // NOI18N
        btnganador.setText("WINNER");
        btnganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnganadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 260, 50));

        txttotalvotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalvotosActionPerformed(evt);
            }
        });
        getContentPane().add(txttotalvotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 70, 30));

        btnsalir.setFont(new java.awt.Font("Cinzel Black", 0, 14)); // NOI18N
        btnsalir.setText("EXIT");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 140, 30));

        lblTituliPrincipal4.setFont(new java.awt.Font("Cinzel Black", 1, 24)); // NOI18N
        lblTituliPrincipal4.setForeground(new java.awt.Color(255, 255, 255));
        lblTituliPrincipal4.setText("Breaking Bad");
        getContentPane().add(lblTituliPrincipal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 190, 40));

        lblTituliPrincipal3.setFont(new java.awt.Font("Cinzel Black", 1, 24)); // NOI18N
        lblTituliPrincipal3.setForeground(new java.awt.Color(255, 255, 255));
        lblTituliPrincipal3.setText("The Sopranos");
        getContentPane().add(lblTituliPrincipal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 210, 40));

        lblTituloGOT.setFont(new java.awt.Font("Cinzel Black", 1, 24)); // NOI18N
        lblTituloGOT.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloGOT.setText("The game of Thrones");
        getContentPane().add(lblTituloGOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 280, 50));

        lblTituliPrincipal1.setFont(new java.awt.Font("Cinzel Black", 1, 36)); // NOI18N
        lblTituliPrincipal1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituliPrincipal1.setText("Nominees");
        getContentPane().add(lblTituliPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, 40));

        lblTituliPrincipal.setFont(new java.awt.Font("Cinzel Black", 1, 48)); // NOI18N
        lblTituliPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTituliPrincipal.setText("Your Choice");
        getContentPane().add(lblTituliPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 350, -1));

        lblsubfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/astronaut-1784245_1280.jpg"))); // NOI18N
        getContentPane().add(lblsubfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 920, 390));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/astronomy-2179083_1280.jpg"))); // NOI18N
        lblfondo.setText("jLabel1");
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 4, 960, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    eleccion participante = new eleccion();
    
    public void borrar(){
        txtgot.setText("");
        txtbbad.setText("");
        txttsop.setText("");
        txtpergot.setText("");
        txtperbbad.setText("");
        txtpertsop.setText("");
        txttotalvotos.setText("");
        participante.contador1=0;
        participante.contador2=0;
        participante.contador3=0;
        participante.porcentaje1=0;
        participante.porcentaje2=0;
        participante.porcentaje3=0;
        participante.totalvotoss=0;
    }    
    public void porcentaje(){
  participante.totalvotoss= participante.getContador1()+participante.getContador2()+participante.getContador3();
       txttotalvotos.setText(String.valueOf(participante.getTotalvotos()));
       //totalvotos =Integer.parseInt(txtTotalVotos.getText());
       //porcentaje1= Integer.parseInt(txtVotos1.getText());
       
       participante.porcentaje1 = participante.getContador1()*100/participante.getTotalvotos();
       txtpergot.setText(String.valueOf(participante.getPorcentaje1()+"%"));
        //porcentaje2= Integer.parseInt(txtVotos2.getText());
       participante.porcentaje2 = participante.getContador2()*100/participante.getTotalvotos();
       txtperbbad.setText(String.valueOf(participante.getPorcentaje2()+"%"));
        //porcentaje3= Integer.parseInt(txtVotos3.getText()); 
       participante.porcentaje3 = participante.getContador3()*100/participante.getTotalvotos();
       txtpertsop.setText(String.valueOf(participante.getPorcentaje3()+"%"));
  }
    
   
    
    private void btngotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngotActionPerformed
        participante.contador1++;
        txtgot.setText(String.valueOf(participante.getContador1()));
        porcentaje();
    }//GEN-LAST:event_btngotActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtpergotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpergotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpergotActionPerformed

    private void btnganadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnganadorActionPerformed
             if  (participante.getContador1()>participante.getContador2() && participante.getContador1()>participante.getContador3()){
           Icon imagen1 = new ImageIcon(getClass().getResource("/IMAGENES/game.jpg"));
       JOptionPane.showMessageDialog(null, "El ganador es: The Game of Thrones"+"\nCon "+participante.getContador1()+" votos.","Ganador de Elecciones",JOptionPane.INFORMATION_MESSAGE,imagen1);
       
       }else if(participante.getContador2()>participante.getContador1() && participante.getContador2()>participante.getContador3()){
           Icon imagen2= new ImageIcon(getClass().getResource("/IMAGENES/breaking.jpg"));
          JOptionPane.showMessageDialog(null, "El ganador es: Breaking Bad"+"\nCon "+participante.getContador2()+" votos.","Ganador de Elecciones",JOptionPane.INFORMATION_MESSAGE,imagen2);
       
       }else if(participante.getContador3()>participante.getContador1() && participante.getContador3()>participante.getContador2()){
           Icon imagen3= new ImageIcon(getClass().getResource("/IMAGENES/soprano.jpg"));
          JOptionPane.showMessageDialog(null, "El ganador es: The Sopranos"+"\nCon "+participante.getContador3()+" votos.","Ganador de Elecciones",JOptionPane.INFORMATION_MESSAGE,imagen3);
       }
            
    }//GEN-LAST:event_btnganadorActionPerformed

    private void txttotalvotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalvotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalvotosActionPerformed

    private void txtgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgotActionPerformed

    }//GEN-LAST:event_txtgotActionPerformed

    private void btnbbadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbbadActionPerformed
 participante.contador2++;
        txtbbad.setText(String.valueOf(participante.getContador2()));
        porcentaje();
    }//GEN-LAST:event_btnbbadActionPerformed

    private void btntsopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntsopActionPerformed
 participante.contador3++;
       txttsop.setText(String.valueOf(participante.getContador3()));
       porcentaje();
    }//GEN-LAST:event_btntsopActionPerformed

    private void txtpertsopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpertsopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpertsopActionPerformed

                                    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_ELECCIONES_JAIRO_SIERRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_ELECCIONES_JAIRO_SIERRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_ELECCIONES_JAIRO_SIERRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_ELECCIONES_JAIRO_SIERRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_ELECCIONES_JAIRO_SIERRA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbbad;
    private javax.swing.JButton btnganador;
    private javax.swing.JButton btngot;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btntsop;
    private javax.swing.JLabel lblBBAD;
    private javax.swing.JLabel lblGOT1;
    private javax.swing.JLabel lblTSOP;
    private javax.swing.JLabel lblTituliPrincipal;
    private javax.swing.JLabel lblTituliPrincipal1;
    private javax.swing.JLabel lblTituliPrincipal3;
    private javax.swing.JLabel lblTituliPrincipal4;
    private javax.swing.JLabel lblTituloGOT;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblperbbad;
    private javax.swing.JLabel lblpergot;
    private javax.swing.JLabel lblpertsop;
    private javax.swing.JLabel lblsubfondo;
    private javax.swing.JLabel lbltotalvotos;
    private javax.swing.JLabel lblvotobbad;
    private javax.swing.JLabel lblvotogot;
    private javax.swing.JLabel lblvototsop;
    private javax.swing.JTextField txtbbad;
    private javax.swing.JTextField txtgot;
    private javax.swing.JTextField txtperbbad;
    private javax.swing.JTextField txtpergot;
    private javax.swing.JTextField txtpertsop;
    private javax.swing.JTextField txttotalvotos;
    private javax.swing.JTextField txttsop;
    // End of variables declaration//GEN-END:variables
}
